[package]
name = "quill"
version = "0.4.1"
authors = ["DFINITY Team"]
edition = "2021"

[[bin]]
name = "quill"
path = "src/main.rs"

[dependencies]
ic-base-types = { git = "https://github.com/dfinity/ic", rev = "5e56d9e6f7da97bbad0ef0269a198e189c6d7120" }
ic-ckbtc-minter = { git = "https://github.com/dfinity/ic", rev = "5e56d9e6f7da97bbad0ef0269a198e189c6d7120" }
ic-nervous-system-common = { git = "https://github.com/dfinity/ic", rev = "5e56d9e6f7da97bbad0ef0269a198e189c6d7120" }
ic-nns-common = { git = "https://github.com/dfinity/ic", rev = "5e56d9e6f7da97bbad0ef0269a198e189c6d7120" }
ic-nns-constants = { git = "https://github.com/dfinity/ic", rev = "5e56d9e6f7da97bbad0ef0269a198e189c6d7120" }
ic-nns-governance = { git = "https://github.com/dfinity/ic", rev = "5e56d9e6f7da97bbad0ef0269a198e189c6d7120" }
ic-sns-governance = { git = "https://github.com/dfinity/ic", rev = "5e56d9e6f7da97bbad0ef0269a198e189c6d7120" }
ic-sns-root = { git = "https://github.com/dfinity/ic", rev = "5e56d9e6f7da97bbad0ef0269a198e189c6d7120" }
ic-sns-swap = { git = "https://github.com/dfinity/ic", rev = "5e56d9e6f7da97bbad0ef0269a198e189c6d7120" }
ic-sns-wasm = { git = "https://github.com/dfinity/ic", rev = "5e56d9e6f7da97bbad0ef0269a198e189c6d7120" }
icp-ledger = { git = "https://github.com/dfinity/ic", rev = "5e56d9e6f7da97bbad0ef0269a198e189c6d7120" }
icrc-ledger-types = { git = "https://github.com/dfinity/ic", rev = "5e56d9e6f7da97bbad0ef0269a198e189c6d7120" }
ledger-canister = { git = "https://github.com/dfinity/ic", rev = "5e56d9e6f7da97bbad0ef0269a198e189c6d7120" }

candid = "0.8.2"
ic-agent = { git = "https://github.com/dfinity/agent-rs", rev = "b9c57f8bab23cc9936dca4560293ffe485471c6d" }
ic-identity-hsm = { git = "https://github.com/dfinity/agent-rs", rev = "b9c57f8bab23cc9936dca4560293ffe485471c6d", optional = true }

anyhow = "1.0.34"
atty = "0.2.14"
base64 = "0.13.0"
bip32 = "0.4.0"
clap = { version = "3.1.18", features = ["derive", "cargo"] }
crc32fast = "1.3.2"
data-encoding = "2.3.3"
flate2 = "1.0.22"
hex = { version = "0.4.2", features = ["serde"] }
hidapi = "1.4"
indicatif = "0.17"
itertools = "0.10.5"
k256 = { version = "0.11.4", features = ["pem"] }
ledger-apdu = "0.10"
ledger-transport-hid = "0.10"
num-bigint = "0.4.3"
once_cell = "1.17.1"
openssl = "0.10.48"
pem = "1.0.1"
qrcodegen = "1.8"
rand = { version = "0.8.4", features = ["getrandom"] }
rpassword = "6.0.0"
rust_decimal = "1.26"
simple_asn1 = "0.6.1"
serde = { version = "1.0.130", features = ["derive"] }
serde_bytes = "0.11.2"
serde_cbor = "0.11.2"
serde_json = "1.0.57"
sha3 = "0.10.6"
tiny-bip39 = "1.0.0"
tokio = { version = "1.18.5", features = ["full"] }

[dev-dependencies]
tempfile = "3.3.0"
shellwords = "1"

[features]
static-ssl = ["openssl/vendored"]
hsm = ["dep:ic-identity-hsm"]
default = ["static-ssl", "hsm"]

[profile.release]
opt-level = 2
