name: CI

on: pull_request

jobs:
  build:
    name: ${{ matrix.task }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [1.60.0]
        task: [check, fmt, clippy, test, build]
    steps:
      - uses: actions/checkout@master

      - name: Install dependencies (windows only)
        if: matrix.os == 'windows-latest'
        shell: bash
        run: |
          vcpkg integrate install
          vcpkg install openssl:x64-windows-static-md
          echo "::set-env OPENSSL_DIR 'C:\Tools\vcpkg\installed\x64-windows-static-md'"
          echo "::set-env OPENSSL_STATIC Yes"
        env:
          VCPKG_ROOT: 'C:\vcpkg'

      - name: Install dependencies (macOS only)
        if: matrix.os == 'macos-latest' && matrix.task == 'build'
        shell: bash
        run: |
          # below steps taken from https://gist.github.com/byronmansfield/97d74d8b0d1ea28b48536020dbd6d53e

          # prepare workspace
          mkdir -p ~/openssl-build/ && cd $_

          # download source code
          curl -LO https://www.openssl.org/source/openssl-1.1.1d.tar.gz

          # expand tar
          tar -xzvf openssl-1.1.1d.tar.gz
          cd openssl-1.1.1d

          # configure, make, install
          perl ./Configure --prefix=/usr/local --openssldir=/usr/local/openssl no-ssl3 no-ssl3-method no-zlib darwin64-x86_64-cc enable-ec_nistp_64_gcc_128
          make
          sudo make install MANDIR=/usr/local/openssl/share/man MANSUFFIX=ssl

          # verify
          openssl version
          which -a openssl

      - name: Link OpenSSL (macOS only)
        if: matrix.os == 'macos-latest' && matrix.task == 'build'
        shell: bash
        run: |
          # see # see https://github.dev/sfackler/rust-openssl/blob/2e986986784f0136d6666a0ef354ff6bafee63eb/openssl/src/lib.rs#L62-L63
          export OPENSSL_STATIC=1
          export OPENSSL_DIR=/usr/local

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - name: ${{ matrix.task }}
        run: make ${{ matrix.task }}
