name: CI

on: pull_request

jobs:
  build:
    name: ${{ matrix.task }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [1.66.1]
        task: [check, fmt, clippy, test]
    steps:
      - uses: actions/checkout@master

      - if: ${{ contains(matrix.os, 'windows') }}
        shell: bash
        run: echo 'VCPKG_ROOT=C:\vcpkg' >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
            ${{ env.VCPKG_ROOT }}
          key: ${{ matrix.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ matrix.rust }}-ci-1

      - name: Install dependencies (windows only)
        if: ${{ contains(matrix.os, 'windows') }}
        shell: bash
        run: |
          vcpkg integrate install
          vcpkg install openssl:x64-windows-static-md
          echo "OPENSSL_DIR=C:\vcpkg\installed\x64-windows-static-md" >> $GITHUB_ENV
          echo "OPENSSL_STATIC=Yes" >> $GITHUB_ENV

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - name: ${{ matrix.task }}
        run: make ${{ matrix.task }}
