name: Check shell scripts

on: pull_request

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install shellcheck
        run: |
          mkdir $HOME/bin
          cd $HOME/bin
          curl -L https://github.com/koalaman/shellcheck/releases/download/v0.7.1/shellcheck-v0.7.1.linux.x86_64.tar.xz \
            | xz -d | tar x
      - name: Check e2e scripts
        run: $HOME/bin/shellcheck-v0.7.1/shellcheck e2e/**/*.*sh
      - name: Check deploy scripts
        run: $HOME/bin/shellcheck-v0.7.1/shellcheck scripts/**/*.sh
  
  aggregate:
    name: shellcheck:required
    needs: [check]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: check result
        if: ${{ needs.check.result != 'success' }}
        run: exit 1
