name: Check shell scripts
on:
  pull_request:
    paths:
      - 'e2e/**'
      - '.github/**'
      - 'scripts/**'
      - 'tests/**'
  push:
    branches: 
      - master
jobs:
  check_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install shellcheck
        run: |
          mkdir $HOME/bin
          cd $HOME/bin
          curl -L https://github.com/koalaman/shellcheck/releases/download/v0.7.1/shellcheck-v0.7.1.darwin.x86_64.tar.xz \
            | xz -d | tar x
      - name: Check e2e scripts
        run: $HOME/bin/shellcheck-v0.7.1/shellcheck e2e/**/*.*sh
      - name: Check deploy scripts
        run: $HOME/bin/shellcheck-v0.7.1/shellcheck scripts/**/*.sh
      - name: Check test scripts
        run: $HOME/bin/shellcheck-v0.7.1/shellcheck -s bash tests/**/*.sh
